#!/usr/bin/env bash
# Regenerate requirements.lock (pinned runtime closure for the Python image).
# Usage: ./scripts/generate-requirements-lock.sh [venv-python]
# Keeps requirements.txt as the human-edited lower bounds; the lock is the
# reproducible snapshot the Dockerfile installs. Dev/test-only distributions
# (pytest, coverage, pip-audit, selenium, …) are excluded via dependency
# closure from the runtime roots — never hand-edited.
set -euo pipefail
PY="${1:-.venv/bin/python}"

"$PY" - <<'EOF'
import importlib.metadata as md
import sys
from packaging.requirements import Requirement

ROOTS = ["ddgs", "fastapi", "uvicorn", "httpx", "cryptography", "keyring"]
EXTRA_CTX = [{"extra": ""}, {"extra": "standard"}]  # uvicorn[standard]

installed = {}
for dist in md.distributions():
    name = (dist.metadata["Name"] or "").lower().replace("-", "_").replace(".", "_")
    if name and name not in installed:
        installed[name] = dist.metadata["Version"]

def canon(req_name):
    return req_name.lower().replace("-", "_").replace(".", "_")

include = {canon(r) for r in ROOTS}
changed = True
while changed:
    changed = False
    for name in list(include):
        dist = None
        for d in md.distributions():
            dname = (d.metadata["Name"] or "").lower().replace("-", "_").replace(".", "_")
            if dname == name:
                dist = d
                break
        if dist is None:
            continue
        for req_str in dist.metadata.get_all("Requires-Dist") or []:
            try:
                req = Requirement(req_str)
            except Exception:
                continue
            if req.marker is None or any(req.marker.evaluate(env) for env in EXTRA_CTX):
                dep = canon(req.name)
                if dep in installed and dep not in include:
                    include.add(dep)
                    changed = True

missing = sorted(n for n in include if n not in installed)
if missing:
    sys.exit(f"lock closure references uninstalled dists: {missing}")

with open("requirements.lock", "w", encoding="utf-8") as fh:
    fh.write(
        "# Generated by scripts/generate-requirements-lock.sh — DO NOT EDIT.\n"
        f"# Roots: {', '.join(ROOTS)} (uvicorn[standard]); "
        f"{sys.version.split()[0]}.\n"
    )
    for name in sorted(include):
        real = next(
            (d.metadata["Name"] for d in md.distributions()
             if (d.metadata["Name"] or "").lower().replace("-", "_").replace(".", "_") == name),
            name,
        )
        fh.write(f"{real}=={installed[name]}\n")
print(f"wrote requirements.lock ({len(include)} pinned runtime distributions)")
EOF
